ShoppeWebApp/ViewModels/Customer/SellerPage.cs
using Microsoft.EntityFrameworkCore;
using ShoppeWebApp.Data;
using ShoppeWebApp.Models;

namespace ShoppeWebApp.ViewModels.Customer
{
    public class SellerPage
    {
        public string IdCuaHang { get; set; } = null!;
        public string TenCuaHang { get; set; } = null!;
        public string UrlAnhCuaHang { get; set; } = null!;
        public int SoSanPhamDangBan { get; set; }
        public string SdtCuaHang { get; set; } = null!;
        public string DiaChiCuaHang { get; set; } = null!;
        public string? MoTaCuaHang { get; set; } = null!;
        public DateTime? ThoiGianThamGia { get; set; } = null!;
        public List<ItemInfo> productInfos = new List<ItemInfo>();
        public List<Danhmuc> categories = null!;
        public string? danhMuc = null;
    }
}

ShoppeWebApp/Areas/Customer/Controllers/SellerPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppeWebApp.Data;
using ShoppeWebApp.Services;
using ShoppeWebApp.ViewModels.Customer;

namespace ShoppeWebApp.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class SellerPageController : Controller
    {
       private readonly ShoppeWebAppDbContext _context;
        public SellerPageController(ShoppeWebAppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int page = 1, string? IdShop = null, string? IdDanhMuc = null, string? searchString = null)
        {
            if(IdShop == null)
            {
                return NotFound();
            }
            var shop = await _context.Cuahangs.FirstOrDefaultAsync(i => i.IdCuaHang == IdShop);
            if(shop == null)
            {
                return NotFound();
            }
            SellerPage sellerPage = new SellerPage
            {
                IdCuaHang = shop.IdCuaHang,
                TenCuaHang = shop.TenCuaHang,
                UrlAnhCuaHang = shop.UrlAnh,
                SoSanPhamDangBan = await _context.Sanphams.CountAsync(i => i.IdCuaHang == IdShop),
                DiaChiCuaHang = shop.DiaChi,
                SdtCuaHang = shop.Sdt,
                MoTaCuaHang = shop.MoTa,
                ThoiGianThamGia = shop.ThoiGianTao,
            };
            var danhMucCoSanPham = await _context.Sanphams
            .Where(i => i.IdCuaHang == IdShop)
            .GroupBy(i => new
            {
                IdDanhMuc = i.IdDanhMuc
            })
            .Select(i => i.Key.IdDanhMuc)
            .ToListAsync();
            sellerPage.categories = await _context.Danhmucs.Where(i => danhMucCoSanPham.Contains(i.IdDanhMuc)).ToListAsync();
            sellerPage.danhMuc = IdDanhMuc;
            var query = _context.Sanphams.Where(i => i.IdCuaHang == IdShop).AsQueryable();

            if(IdDanhMuc != null)
            {
                query = query.Where(i => i.IdDanhMuc == IdDanhMuc);
            }
            if(searchString != null)
            {
                searchString = searchString.ToUpper();
                query = query.Where(i => i.TenSanPham.ToUpper().Contains(searchString));
            }

            int totalProducts = await query.CountAsync();

            int totalPage = totalProducts % Constants.PAGINATION_SIZE == 0?
                totalProducts / Constants.PAGINATION_SIZE
                :totalProducts / Constants.PAGINATION_SIZE + 1;
            if (totalPage != 0 && (page < 1 || page > totalPage))
            {
                return NotFound();
            }

            var pros = await query.OrderBy(i => i.IdSanPham)
                .Skip((page - 1) * Constants.PAGINATION_SIZE)
                .Take(Constants.PAGINATION_SIZE).ToListAsync();

            foreach (var i in pros)
            {
                sellerPage.productInfos.Add(new ItemInfo
                {
                    IdSanPham = i.IdSanPham,
                    TenSanPham = i.TenSanPham,
                    UrlAnh = i.UrlAnh,
                    GiaBan = i.GiaBan,
                    DiemDanhGia = i.SoLuongDanhGia > 0? i.TongDiemDanhGia / i.SoLuongDanhGia: 0,
                    SoLuongBan = Quantity.ProcessQuantity(i.SoLuongBan),
                });
            }
            ViewBag.PagingInfo = PagingLoad.GetPaging(totalPage, page);
            ViewBag.Page = page;
            ViewBag.IdDanhMuc = IdDanhMuc;
            return View(sellerPage);
        }
    }
}

ShoppeWebApp/Areas/Customer/Views/SellerPage/Index.cshtml
@model SellerPage;
@{
	ViewData["Title"] = Model.TenCuaHang;
}
<div class="template-2">
	<div class="container-2">
		<div class="bg-white box-padding-left-right-20 border-rounded gh-grid">
			<div class="shop-side box-padding-top-bottom-20">
				<div class="bg-FBFBFB box-padding-20 border-rounded product-main-info-store">
					<div class="d-flex gap-4">
						<div class="box-padding-15">
							<img src="@Model.UrlAnhCuaHang" class="circle-img">
						</div>
						<div class="d-flex flex-column justify-content-center">
							<div class="product-main-info-store-name">@Model.TenCuaHang</div>
							<table class="product-main-info-stat">
								<tr>
									<td class="min-width-150">Sản phẩm đang bán:</td>
									<td>@Model.SoSanPhamDangBan</td>
								</tr>
								<tr>
									<td>Đã tham gia vào:</td>
									<td>@Model.ThoiGianThamGia?.ToString("dd/MM/yyyy")</td>
								</tr>
								<tr>
									<td>Địa chỉ cửa hàng:</td>
									<td>@Model.DiaChiCuaHang</td>
								</tr>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="shop-desc-side bg-white box-padding-20 border-rounded product-main-info-store">
				<div class="product-main-info-store-name" style="margin-top: 20px;">Mô tả cửa hàng</div>
				<div>
					@Model.MoTaCuaHang
				</div>
			</div>
		</div>

		<div class="gh-grid mt-4">
			<div class="sidebar">
				<div class="bg-white d-flex flex-column overflow-hidden border-rounded">
					<div class="bg-white flex-column container-3">
						<div class="tab-header">Tất cả danh mục</div>
						<ul class="nostyle-ul">
							@foreach (var i in Model.categories)
							{
								<li>
									<a asp-area="Customer" asp-controller="SellerPage" asp-action="Index" asp-route-IdShop="@Model.IdCuaHang" asp-route-IdDanhMuc="@i.IdDanhMuc" class="tab-link">
										<div class="truncate">
											@if (Model.danhMuc == i.IdDanhMuc)
											{
												<div class="fw-bold"> @i.TenDanhMuc </div>
											}
											else
											{
												@i.TenDanhMuc
											}
										</div>
									</a>
								</li>
							}
						</ul>
					</div>
				</div>
			</div>
			<div class="products-container">
				<form asp-controller="SellerPage" asp-action="Index" method="get" class="user-search-form">
					<input name="IdShop" value="@Model.IdCuaHang" type="hidden" />
					<input name="IdDanhMuc" value="@ViewBag.IdDanhMuc" type="hidden" />
					<input type="text" name="searchString" value="@Context.Request.Query["searchString"]"
						   placeholder="Tìm kiếm sản phẩm trong cửa hàng"
						   class="user-search-input" />
					<button type="submit" class="user-search-button">Tìm</button>
				</form>
				<div>
					<ul class="products-list nostyle-ul">
						@foreach (var item in Model.productInfos)
						{
							<li>
								<div class="zoom-wrapper d-flex flex-column border-rounded overflow-hidden bg-white my-card">
									<a asp-controller="Product" asp-action="index" asp-route-id="@item.IdSanPham" class="tab-link-2">
										<div class="graphic-cover border-style-3">
											<img src="~/@item.UrlAnh" style="height: 230px;" />
										</div>
										<div class="d-flex flex-column box-padding-10 row-gap-1">
											<div class="break-word line-clamp-2 min-height-3">
												@item.TenSanPham
											</div>
											<div class="d-flex">
												<div class="truncate min-width-1 text-style-2">
													@string.Format("{0:#,##0} ₫", item.GiaBan)
												</div>
												<div class="ms-auto d-flex flex-column justify-content-center">
													<div class="truncate min-width-1 text-style-3 text-end">
														@string.Format("Đã bán {0}", item.SoLuongBan)
													</div>
												</div>
											</div>
										</div>
									</a>
								</div>
							</li>
						}
					</ul>
				</div>
				<div class="d-flex justify-content-center gap-3">
					@foreach (var i in ViewBag.PagingInfo)
					{
						if (@i.Value != null)
						{
							if (i.Value != null && ViewBag.Page == i.Value)
							{
								<strong>
									<a asp-area="Customer" asp-controller="SellerPage"
									   asp-action="Index"
									   asp-route-page="@i.Value"
									   asp-route-IdShop="@Model.IdCuaHang"
									   asp-route-IdDanhMuc="@Model.danhMuc"
									   class="tab-link">
										<div>@i.Name</div>
									</a>
								</strong>
							}
							else
							{
								<a asp-area="Customer" asp-controller="SellerPage"
								   asp-action="Index" asp-route-page="@i.Value"
								   asp-route-IdShop="@Model.IdCuaHang"
								   asp-route-IdDanhMuc="@Model.danhMuc"
								   class="tab-link">
									<div>@i.Name</div>
								</a>
							}
						}
						else
						{
							<a>...</a>
						}
					}
				</div>
			</div>
		</div>
	</div>
</div>